name: Pull Request Meta

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  process_pr_meta:
    name: Process PR meta
    runs-on: ubuntu-24.04
    steps:
      - name: Assign to author
        uses: toshimaru/auto-author-assign@4d585cc37690897bd9015942ed6e766aa7cdb97f # v3.0.1

      - name: Add labels
        uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af # v5.0.0
        with:
          configuration-path: .github/pr-labeler.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
